Media query on complexes page
kolombet/yard-frontend pull request #10
Opened 2017-07-22 20:24 UTC by kolombet

2017-07-22 20:48 UTC, kolombet commented
https://kolombet-yard-frontend.now.sh/

2017-07-22 20:53 UTC, kolombet commented
вроде домен забиндился, но что то не обновляется
на всякий случай ссылка 
https://yard-frontend-oxjqsetwls.now.sh
<img width="767" alt="2017-07-22 23 53 24" src="https://user-images.githubusercontent.com/672998/28494488-fc146dfa-6f38-11e7-91b9-822244b945d3.png">

2017-07-24 11:07 UTC, evgenyrodionov commented
Немного неприятно что на планшете ведет себя так

![image](https://user-images.githubusercontent.com/775692/28520750-738b9980-7079-11e7-827b-ff8f40c50a22.png)

2017-07-24 11:21 UTC, imevro requested changes
раздели на два ПРа

2017-07-24 20:18 UTC, kolombet commented
Под планшет буду завтра переверстывать, похоже где то накосячил с xs sm md... 
Залил версию под телефоны, хотелось бы по ней косяки узнать, чтобы тоже править
yard-frontend-jpxakztcvb.now.sh

2017-07-24 22:45 UTC, evgenyrodionov commented
Вот тут не оч

![image](https://user-images.githubusercontent.com/775692/28548058-959bea82-70da-11e7-8718-b4f4aa896d5e.png)

Тут какой-то андерлайн у ссылки 

![image](https://user-images.githubusercontent.com/775692/28548068-9f1235ee-70da-11e7-9924-f45663d66432.png)

А почему карта до сих пор не мапбокс?

![image](https://user-images.githubusercontent.com/775692/28548080-a89b0708-70da-11e7-881a-33944ddda52a.png)

![mobile 2017-07-25 01-44-28](https://user-images.githubusercontent.com/775692/28548116-e3a1bafe-70da-11e7-842b-9359de8f94aa.png)

2017-07-25 20:26 UTC, kolombet commented
https://kolombet-yard-frontend.now.sh/

2017-07-26 07:20 UTC, kolombet commented
Перезапустил travis, он корректно сбилдил со второй попытки. Вчера билд долго висел, я не дождался, спать ушел :(

2017-07-26 08:01 UTC, evgenyrodionov commented
А почему ты деплоишь на основной домен то, что не закончено?

2017-07-26 08:04 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28610758-233fee20-71f2-11e7-8733-a54c45a0e7d7.png)

2017-07-26 08:06 UTC, evgenyrodionov commented
Поправь планшет

2017-07-26 08:12 UTC, imevro requested changes

2017-07-26 08:12 UTC, evgenyrodionov commented on src/App.jsx
> +        <Route exact path="/" component={() => <Redirect from="/" to="/complexes" />} />
не понял

2017-07-26 08:12 UTC, evgenyrodionov commented on src/Complexes/List/Contact.jsx
> +    width: 804px;
нельзя

2017-07-26 08:12 UTC, evgenyrodionov commented on src/Complexes/Show/Guide.jsx
> +          <MapBox lat={-122.65} long={45.52} />
откуда взял, в апи же есть

2017-07-26 08:12 UTC, evgenyrodionov commented on src/Complexes/Show/MapBox.jsx
> +    'pk.eyJ1IjoieGVucmVhbCIsImEiOiJjajVqdzF2cnAyZXlqMzJwa3BheTl4emVtIn0.Yfal-PngDVEmMcURuE2ulg',
энв-параметром, никогда не храни креденшлс в коде

2022-12-12 09:09 UTC, closed without merging