Created complexes page
kolombet/yard-frontend pull request #2
Opened 2017-06-27 20:15 UTC by kolombet

2017-06-27 23:44 UTC, imevro requested changes

2017-06-27 23:44 UTC, evgenyrodionov commented on complexes.html
> +<header class="header">
а чё отступы уехали

2017-06-27 23:44 UTC, evgenyrodionov commented on complexes.html
> +    <img class="compass-logo" src="img/compass-logo.svg">
.header-wrapper > .compass-logo + .navigation? вообще несогласованный нейминг

2017-06-27 23:44 UTC, evgenyrodionov commented on complexes.html
> +  <div class="column-wrapper header-wrapper">
что такое column-wrapper? какой-то мусорный несемантичный неочевидный класс

2017-06-27 23:44 UTC, evgenyrodionov commented on complexes.html
> +<section class="column-wrapper row center-md">
даже если ты оставишь этот колумн враппер, мы не смешиваем свои классы и классы сетки

2017-06-27 23:44 UTC, evgenyrodionov commented on style.css
> +:root {
странный селектор, когда можно на бади повесить

2017-06-27 23:44 UTC, evgenyrodionov commented on style.css
> +.column-wrapper {
в фбг есть .container

2017-06-27 23:44 UTC, evgenyrodionov commented on style.css
> +  height: 2.5rem;
это откуда взялось

2017-06-28 06:12 UTC, kolombet commented on style.css
> +.column-wrapper {
Только вот .container шириной не 75rem (1200px как на макете), а 76rem, из за чего верстка по ширине не совпадает с макетом.

2017-06-28 15:08 UTC, imevro requested changes

2017-06-28 15:08 UTC, evgenyrodionov commented on complexes.html
> +          <div class="footer-description">
зачем этот див если классы можно вешать на тег параграфа

2017-06-28 15:08 UTC, evgenyrodionov commented on complexes.html
> +          <div class="footer-line"></div>
почему див, а не hr

2017-06-28 15:08 UTC, evgenyrodionov commented on complexes.html
> +          <a class="footer-link footer-all" href="#">Все ЖК Москвы &#x2192;</a>
почему не иконкой

2017-06-28 15:08 UTC, evgenyrodionov commented on complexes.html
> +        <div class="col-md-2 footer-contact">
читай чужие пры

2017-06-28 15:08 UTC, evgenyrodionov commented on style.css
> +.body {
зачем классом

2017-06-28 16:30 UTC, kolombet commented on style.css
> +.body {
для консистентности. мы же не вешаем стили на тэги? или это исключение из правил?

2017-06-28 16:33 UTC, kolombet commented on complexes.html
> +          <div class="footer-line"></div>
на hr изначально висит много лишних стилей, которые надо переписывать (ненулевые margin)

2017-06-28 18:24 UTC, evgenyrodionov commented
https://rawgit.com/kolombet/yard-frontend/develop2/complexes.html

![image](https://user-images.githubusercontent.com/775692/27653554-17627466-5c48-11e7-9f30-d91978731e20.png)
![image](https://user-images.githubusercontent.com/775692/27653560-1f26b7a2-5c48-11e7-86d0-cf032cf3e3de.png)
![image](https://user-images.githubusercontent.com/775692/27653570-26815778-5c48-11e7-94ea-dfb8d50e1904.png)

2017-06-29 13:33 UTC, imevro requested changes

2017-06-29 13:33 UTC, evgenyrodionov commented on complexes.html
> +        <div class="col-md-2 footer-contact">
мы не смешиваем сетку и наши классы

2017-06-29 13:33 UTC, evgenyrodionov commented on style.css
> +.column-wrapper {
можно дропнуть в пользу .container

2017-06-29 13:33 UTC, evgenyrodionov commented on style.css
> +  margin-top: 5.938rem;
какое-то лютое значение

2017-06-29 13:33 UTC, evgenyrodionov commented on style.css
> +  margin-top: 5.938rem;
в макете же 96пкс отступ, а это 96/16 = 6рем

2017-06-29 13:33 UTC, evgenyrodionov commented on style.css
> +  margin-bottom: 1.938rem;
опять же

2017-06-29 14:53 UTC, kolombet commented on style.css
> +  margin-top: 5.938rem;
В макете 95px, но наверное можно округлить до 96, чтобы соответствовать стандартам

2017-06-29 16:51 UTC, imevro requested changes

2017-06-29 16:51 UTC, evgenyrodionov commented on style.css
> +  margin-left: .5rem;
объясни необходимость?

2017-06-29 17:17 UTC, kolombet commented on style.css
> +  margin-left: .5rem;
У flexboxgrid класс .container шириной 76rem, макет у нас 75rem. Соответственно я каждому контейнеру добавляю margin-left: .5rem; margin-right: .5rem, для того, чтобы верстка соответствовала макету.

2017-06-30 09:38 UTC, imevro approved these changes

2017-06-30 09:38 UTC, merged