Ported html to react, created two pages with small components.
kolombet/yard-frontend pull request #4
Opened 2017-07-03 16:54 UTC by kolombet

2017-07-04 09:41 UTC, imevro requested changes
Плохая архитектура

Объединяй по бизнес-сущностям, а не мусорку в src устраивай. У тебя есть 1 сущность — жилые комплексы, она делится на список и show страницы.

2017-07-04 09:41 UTC, evgenyrodionov commented on package.json
> +  "name": "app",
переименуй

2017-07-04 09:41 UTC, evgenyrodionov commented on public/index.html
> +    <title>React App</title>
опять же

2017-07-04 09:41 UTC, evgenyrodionov commented on src/App.js
> +          <Route exact path='/' component={Complexes}/>
Поставь преттир в редактор

2017-07-04 09:41 UTC, evgenyrodionov commented on src/Offers.js
> +            <Offer title="1-комнатные квартиры" area="от 59 до 120 м²" price="от 20.3 до 84.2 млн руб"/>
Передавай area и prices как джс объект с ключами min max

2017-07-04 09:41 UTC, evgenyrodionov commented on src/Offers.js
> +            <Offer title="1-комнатные квартиры" area="от 59 до 120 м²" price="от 20.3 до 84.2 млн руб"/>
тайтл в общем-то тоже

2017-07-04 09:41 UTC, evgenyrodionov commented on src/Offers.js
> +      <section className="offer">
offer или offers?

2017-07-04 09:41 UTC, evgenyrodionov commented on src/Offers.js
> +import React, {Component} from 'react';
положи в директорию Offers и используй как `/Offers/index.jsx` и `/Offers/Card.jsx`

2017-07-04 09:41 UTC, evgenyrodionov commented on src/LineShort.js
> +      <div className="line-short"/>
почему див? hr на что дали?

2017-07-04 09:41 UTC, evgenyrodionov commented on src/LineShort.js
> +class LineShort extends Component {
слабый нейминг компонента

2017-07-04 09:41 UTC, evgenyrodionov commented on src/GuideItem.js
> +        <p className="guide-navigation-details">{this.props.details}</p>
это не детейлс, это время в пути и кол-во километров

2017-07-04 09:41 UTC, evgenyrodionov commented on src/GuideItem.js
> +        <h3 className="guide-navigation-title">{this.props.title}</h3>
это не тайтл

2017-07-04 09:41 UTC, evgenyrodionov commented on src/GuideItem.js
> +class GuideItem extends Component {
хуитем

2017-07-04 09:41 UTC, evgenyrodionov commented on src/Guide.js
> +class Offer extends Component {
??

2017-07-04 21:46 UTC, imevro requested changes

2017-07-04 21:46 UTC, evgenyrodionov commented on src/Complexes/Show/BuildingInfoMainItem.js
> +class BuildingInfoTitle extends Component {
что с неймингом раз

2017-07-04 21:46 UTC, evgenyrodionov commented on src/Complexes/Show/BuildingInfoMainItem.js
> +class BuildingInfoTitle extends Component {
зачем этот компонент-прокладка два

2017-07-04 21:46 UTC, evgenyrodionov commented on src/Complexes/Show/index.js
>  import BuildingInfoTitle from './BuildingInfoTitle';
зачем вот эти префиксы билдингинфо?

2017-07-04 23:50 UTC, kolombet commented on src/Complexes/Show/BuildingInfoMainItem.js
> +class BuildingInfoTitle extends Component {
"разбивать страницы на крупные компоненты-этажи". Предполагаю, что каждый логически несвязанный с другими контэйнер на странице это "этаж". Удобно это будет тем, что у каждого "этажа" можно будет создать свой стиль Title для заголовка с одинаковым названием, но разными стилями.

2017-07-04 23:53 UTC, kolombet commented on src/Complexes/Show/BuildingInfoMainItem.js
> +class BuildingInfoTitle extends Component {
То что сейчас названия компонентов не соответствуют названиям стилей в верстке - временное явление. В стилях названия не везде удачные, хочу назвать компоненты хорошо и лаконично. Переименовывать названия в стилях - сизифов труд, так как все равно стили будут заменены на styled-components с совершенно другим нэймингом.

2017-07-05 11:26 UTC, imevro requested changes

2017-07-05 11:26 UTC, evgenyrodionov commented on package.json
> +  "name": "app",
И?

2017-07-05 16:48 UTC, kolombet commented on package.json
> +  "name": "app",
Странно, точно помню, что фиксил. Похоже что куда-то потерял коммит.

2017-07-05 18:13 UTC, imevro requested changes

2017-07-05 18:13 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
а тут?

2017-07-05 18:13 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +export default props =>
отступы делай от импортов

2017-07-05 18:13 UTC, evgenyrodionov commented on src/HorizontalLine.js
> +class HorizontalLine extends Component {
функцией тогда уж

2017-07-05 18:13 UTC, evgenyrodionov commented on src/HorizontalLine.js
> +class HorizontalLine extends Component {
и сразу экспорт

2017-07-05 21:36 UTC, imevro approved these changes

2017-07-05 21:36 UTC, merged

2017-07-05 21:37 UTC, evgenyrodionov commented
делай бранч от мастера, не забудь гит пулл --ребейз и все остальное