Api integration complete
kolombet/yard-frontend pull request #7
Opened 2017-07-12 22:37 UTC by kolombet

2017-07-13 09:12 UTC, evgenyrodionov commented
1) коммиты после ревью
2) где деплой, как тестить

2017-07-13 14:59 UTC, kolombet commented
https://build-bauvzkemsz.now.sh

2017-07-13 15:03 UTC, kolombet commented
https://build-icvyqmrakz.now.sh

2017-07-13 21:40 UTC, evgenyrodionov commented
- описание есть в .fullDescription, .shortDescription
- инфраструктура в amenities
- Предложения в ЖК «Полянка/44» в Монэ?

![compass development 2017-07-14 00-39-19](https://user-images.githubusercontent.com/775692/28189047-00b0e914-682d-11e7-8ec5-8ae7d8b29f63.png)

2017-07-15 06:56 UTC, kolombet commented
https://build-zibkbnptzm.now.sh

2017-07-15 13:04 UTC, evgenyrodionov commented
Куда делись отступы 

![image](https://user-images.githubusercontent.com/775692/28239536-4618efb0-6977-11e7-92df-f894ceb6c021.png)

2017-07-15 13:09 UTC, imevro requested changes
адок

2017-07-15 13:09 UTC, evgenyrodionov commented on package.json
> +    "number-to-fixed": "^1.0.0",
бля

2017-07-15 13:09 UTC, evgenyrodionov commented on package.json
> +    "number-to-fixed": "^1.0.0",
не ставь такую мелкую хуйню

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +export default function CardComponent(props) {
зачем постфикс компонент

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/List/Card.jsx
> +CardComponent.propTypes = {
выкинь проптайпс

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +        {this.state.complexes.filter(complex => !isDraft(complex.state)).map((complex) => {
красава, но я уже говорил что у апи есть возможность фильтровать на его уровне

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +              description={fullDescription}
зачем в карточку фуллдескрипшен на 3 абзаца передавать?

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +export default function CharacteristicsComponent(props) {
не делай эти постфиксы компонент

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/Show/Description.jsx
> +  if (!props.text || props.text.length === 0) return null;
Не надо условия в стиле йоды писать. Сначала true, потом false, а не наоборот

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    const { furniture, condition, renovate } = information;
читай чужие пры

2017-07-15 13:09 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    const characteristics = {
ох пиздец

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +import toFixed from 'number-to-fixed';
у тебя файл-мусорка получился

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +} from './complexes-dictionaries';
почему не `./Complexes/dictionary.js`?

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +export const getSecurity = type => securityKinds[type] || '';
што-то ад, зачем тут это

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +export const isLocalMode = false;
зачем почему к чему это усложнение

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +    setTimeout(() => {
таймаут зачем??

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +export const getPhotoLocale = (count) => {
а если я захочу склонять не только это?

2017-07-15 13:09 UTC, evgenyrodionov commented on src/util.jsx
> +export const getPhotoLocale = (count) => {
гугли плюралайзер

2017-07-15 16:07 UTC, kolombet commented
https://build-xveyfxxpee.now.sh

2017-07-15 16:12 UTC, kolombet commented
https://build-sqnhreoivh.now.sh

2017-07-15 17:29 UTC, imevro requested changes

2017-07-15 17:29 UTC, evgenyrodionov commented on src/Complexes/Show/Gallery.jsx
> +            {`${length} ${count}`}
можно без интерполяции обойтись

2017-07-15 17:29 UTC, evgenyrodionov commented on src/Complexes/Show/Infrastructures.jsx
> +            {props.infrastructures.map(amenitie =>
amenitie?

2017-07-15 17:29 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    if (this.state.complex) {
мне не нравится такой подход, вся страница флэшнется

2017-07-15 17:29 UTC, evgenyrodionov commented on src/api.jsx
> +export const get = (resource, filter = '') =>
а че так слиплось всё, дай воздуха

2017-07-15 17:29 UTC, evgenyrodionov commented on src/api.jsx
> +export const getComplexes = () => get('complexes', FILTER_PUBLIC);
а зачем эти функции?

2017-07-15 17:29 UTC, evgenyrodionov commented on src/api.jsx
> +export const getComplexes = () => get('complexes', FILTER_PUBLIC);
Нормально в том месте где используешь делать сразу `get('/v1/complexes?filter...')`, а так тебе нужно зачем-то мейнтейнить функции тут

2017-07-15 17:29 UTC, evgenyrodionov commented on src/index.js
> +import WebFont from 'webfontloader';
а зачем? Не понимаю

2017-07-15 17:56 UTC, kolombet commented on src/api.jsx
> +export const getComplexes = () => get('complexes', FILTER_PUBLIC);
а когда появится v2 в котором измен метод (или даже удален), по всем файлам искать где он используется?

2017-07-15 18:00 UTC, kolombet commented on src/index.js
> +import WebFont from 'webfontloader';
Проверил сайт с помощью плагина lighthouse от google. Оно говорит что стили в head блочат рендер. А зачем мы тогда вынесли от туда normalize и flexboxgrid?
<img width="827" alt="2017-07-15 20 59 14" src="https://user-images.githubusercontent.com/672998/28241608-84b34652-69a0-11e7-8fc8-4d3dd7d9478f.png">

2017-07-15 18:01 UTC, evgenyrodionov commented on src/index.js
> +import WebFont from 'webfontloader';
потому что нормалайз лучше из нпма подключать, а фбг у нас вообще реакт-фбг

2017-07-15 18:01 UTC, evgenyrodionov commented on src/index.js
> +import WebFont from 'webfontloader';
типа зачем подключать нормалайз из сдна, если есть пекейджджсон где можно обновлять зависимости

2017-07-15 18:40 UTC, kolombet commented on src/Complexes/Show/Gallery.jsx
> +            {`${length} ${count}`}
в интерполяцию превращает prettier автоматически при сохранении

2017-07-15 18:40 UTC, kolombet commented on src/Complexes/Show/Gallery.jsx
> +            {`${length} ${count}`}
предпочитаю интерполяцию,  ${length + " " + count} выглядит не очень, а если еще и добавить что нибудь придется, все равно на интерполяцию менять

2017-07-15 18:44 UTC, kolombet commented on src/Complexes/Show/Gallery.jsx
> +            {`${length} ${count}`}
ааа, можно было вот так просто {length} {count}

2017-07-15 20:18 UTC, kolombet commented
https://build-uoumdcscfr.now.sh

2017-07-15 20:47 UTC, evgenyrodionov commented on src/api.jsx
> +export const getComplexes = () => get('complexes', FILTER_PUBLIC);
в том-то и дело, что обычно держат две версии апи и переводят постепенно

2017-07-15 20:51 UTC, imevro requested changes

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
а зачем это константой держать не понимаю

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
а также зачем ТАК_ОРАТЬ

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
а также почему getApi функция называется в api.js

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/Show/Amenities.jsx
> +import Amenitie from './Amenitie';
Amenitie?

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/Show/Amenities.jsx
> +          {props.amenities.length > 0 && <Title>Инфраструктура</Title>}
вынеси эту проверку в индекс и ваще не рендерь компонент

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +const Empty = styled.div``;
не понял

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +const Empty = styled.div``;
понял

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +const Empty = styled.div``;
замечание то же что и выше

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +    getApi(`complexes/${slug}`).then((json) => {
говорил про в1

2017-07-15 20:51 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
http://npm.im/qs btw

2017-07-15 21:09 UTC, kolombet commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
get плохо, getApi плохо. вот даже не знаю, может makeApiRequest (слишком длинно)? или покороче, что нибудь load (тоже слишком коротко)

2017-07-15 21:10 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
а с чего ты взял что гет плохо?

2017-07-15 21:11 UTC, kolombet commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
вообще функции надо глаголами называть, поэтому api не походит. makeRequest по моему оптимально

2017-07-15 21:12 UTC, kolombet commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
посмотрел, в facebook api обращение к api идет методом api. значит, наверное, можно и без глагола

2017-07-15 21:13 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
называй по методам и всё

2017-07-15 21:13 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +import { getApi, FILTER_PUBLIC } from '../../api';
get / post / put / del

2017-07-15 21:28 UTC, kolombet commented
https://build-tkosutlvoz.now.sh

2017-07-16 07:25 UTC, kolombet commented
https://build-bqluyzygsq.now.sh

2017-07-16 07:44 UTC, kolombet commented
https://build-bqluyzygsq.now.sh

2017-07-17 10:01 UTC, imevro requested changes

2017-07-17 10:01 UTC, evgenyrodionov commented on src/App.jsx
> +        <Route exact path="/" component={() => <Redirect to="/complexes/list" />} />
А просто `<Redirect from="/" to="/complexes" />` не сработает?

2017-07-17 10:01 UTC, evgenyrodionov commented on src/App.jsx
> +        <Route exact path="/complexes/list" component={List} />
Без лист

2017-07-17 10:01 UTC, evgenyrodionov commented on src/App.jsx
> +        <Route path="/complexes/show/:slug" component={Show} />
и без шоу

2017-07-17 10:01 UTC, evgenyrodionov commented on src/App.jsx
> +        <Route path="/complexes/show/:slug" component={Show} />
можно просто /complexes и /complexes/:slug, это достаточно понятно

2017-07-17 10:01 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +    get('complexes?filter[state]=public').then((json) => {
воспользуйся пакетом qs, говорю же

2017-07-17 10:01 UTC, evgenyrodionov commented on src/api.jsx
> +const API_URL = 'https://yard.moscow/api/v1/';
и все же зачем ТАК_ОРАТЬ

2017-07-17 10:01 UTC, evgenyrodionov commented on src/api.jsx
> +const API_URL = 'https://yard.moscow/api/v1/';
Что мешает назвать `baseUrl`?

2017-07-17 10:14 UTC, kolombet commented on src/App.jsx
> +        <Route exact path="/" component={() => <Redirect to="/complexes/list" />} />
Пробовал, не работает.

2017-07-17 10:20 UTC, kolombet commented on src/api.jsx
> +const API_URL = 'https://yard.moscow/api/v1/';
У Airbnb на эту тему ничего не нашел, мозилла рекомендует uppercase. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const // NOTE: Constants can be declared with uppercase or lowercase, but a common
// convention is to use all-uppercase letters.

2017-07-17 10:21 UTC, evgenyrodionov commented on src/api.jsx
> +const API_URL = 'https://yard.moscow/api/v1/';
Почему тогда get, а не GET?

2017-07-17 11:33 UTC, kolombet commented on src/App.jsx
> +        <Route exact path="/" component={() => <Redirect to="/complexes/list" />} />
Видимо как то не так пробовал, теперь работает...

2017-07-17 11:46 UTC, kolombet commented on src/api.jsx
> +const API_URL = 'https://yard.moscow/api/v1/';
Потому что airbnb rule 23.2 Use camelCase when naming objects, functions, and instances.
Но вообще, наверное, строка тоже считается объектом в js, поэтому к ней тоже применяется это правило. Странно, что eslint не ругался. пофиксил

2017-07-17 12:08 UTC, kolombet commented
https://build-cjztfwykpe.now.sh

2017-07-17 12:09 UTC, kolombet commented
https://build-cjztfwykpe.now.sh

2017-07-17 17:03 UTC, imevro approved these changes

2017-07-17 17:03 UTC, merged