Travis integration complete
kolombet/yard-frontend pull request #8
Opened 2017-07-17 12:50 UTC by kolombet

2017-07-17 16:55 UTC, kolombet commented
https://kolombet-yard-frontend.now.sh/

2017-07-17 17:17 UTC, evgenyrodionov commented
Так он сам должен деплоить при пуше в мастер

2017-07-17 17:17 UTC, imevro requested changes
хорошо, но докрути

2017-07-17 17:17 UTC, evgenyrodionov commented on .travis.yml
> +  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
он сам поставит ярн

2017-07-17 17:17 UTC, evgenyrodionov commented on .travis.yml
> +  - yarn global add now
не ставь в глобал, ставь в девдепс, он и так у тебя есть вроде

2017-07-18 11:23 UTC, evgenyrodionov commented
У тебя получилось повторить это локально?

2017-07-18 11:26 UTC, kolombet commented
Как повторить? При пуше в ветку travis деплой я тестировал, срабатывало. Полагаю что и при мердже должно сработать

2017-07-18 11:27 UTC, kolombet commented
Можно попробовать отдельный репозиторий создать в нем потестировать, наверное

2017-07-18 11:31 UTC, evgenyrodionov commented
Не, я имел в виду руками прописать шаги из трэвиса у себя локально

2017-07-18 11:32 UTC, evgenyrodionov commented
Но да, попробуй в отдельном репо

2017-07-18 16:53 UTC, kolombet commented
поправил, работает

2017-07-19 08:48 UTC, merged