Flowtype integration complete
kolombet/yard-frontend pull request #9
Opened 2017-07-18 16:51 UTC by kolombet

2017-07-19 09:12 UTC, imevro requested changes
В целом хорошо, очень даже

2017-07-19 09:12 UTC, evgenyrodionov commented on .eslintrc.json
> +    "strict": 0
почему

2017-07-19 09:12 UTC, evgenyrodionov commented on package.json
> +    "flow-typed": "./node_modules/.bin/flow-typed"
Можно просто `flow-typed`, ярн/нпм сами лезут в `./node_modules/.bin/`

К `lint` выше тоже относится кстати

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +type State = Array<ComplexType> | Array;
можно просто `Array<ComplexType>`

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +  state:State;
объяви через классовый проперти

`state: State = []`

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +  state:State;
или как-то так

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +        {this.state.complexes.map((complex: ComplexType) => {
а как ты итерируешься по state.complexes?

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +        {this.state.complexes.map((complex: ComplexType) => {
если его больше нет

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +    this.state = [];
на самом деле не уверен что хранить стейт массивом это хорошая затея

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
> +    this.state = [];
если тебе понадобится пагинация, куда её положишь?

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/Show/Characteristics.jsx
> +const defaultInformation = {
я бы не делал так, потому что покупателя можешь ввести в заблуждение если брокер проебется и не задаст значение

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/types.js
> +export type GalleryImageType = {
тут так-то тоже есть width/height

2017-07-19 09:12 UTC, evgenyrodionov commented on src/Complexes/types.js
> +export type ComplexType = {
в целом почитай модель внимательнее

2017-07-21 18:01 UTC, imevro requested changes

2017-07-21 18:01 UTC, evgenyrodionov commented on src/Complexes/List/Cards.jsx
>      get(`complexes?${filter}`).then((data) => {
делай отступ между константами и кодом

2017-07-21 18:01 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
>      get(`complexes/${slug}`).then((data: ComplexType) => {
используй object shorthand тогда

2017-07-21 18:01 UTC, evgenyrodionov commented on src/Complexes/Show/index.jsx
> +  props: {
вынеси в type Props

2017-07-22 09:47 UTC, imevro requested changes

2017-07-22 09:47 UTC, evgenyrodionov commented on package.json
> +    "prepush": "eslint && flow",
это бинарники запускает, не нпм-скрипты

2017-07-22 11:53 UTC, kolombet commented on package.json
> +    "prepush": "eslint && flow",
пофиксил

2017-07-22 17:49 UTC, imevro approved these changes

2017-07-22 17:49 UTC, merged